// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ecommerce.persistence.SqlServer;

#nullable disable

namespace ecommerce.persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250423152311_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ecommerce.domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-1234-5678-9012-345678901234"),
                            Category = "Điện tử",
                            CreatedAt = new DateTime(2025, 4, 23, 15, 23, 11, 154, DateTimeKind.Utc).AddTicks(4855),
                            Description = "Flagship smartphone",
                            Name = "iPhone 15 Pro",
                            Price = 1299.99m,
                            StockQuantity = 100,
                            UpdatedAt = new DateTime(2025, 4, 23, 15, 23, 11, 154, DateTimeKind.Utc).AddTicks(4857)
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-2345-6789-0123-456789012345"),
                            Category = "Máy tính",
                            CreatedAt = new DateTime(2025, 4, 23, 15, 23, 11, 154, DateTimeKind.Utc).AddTicks(4860),
                            Description = "Laptop cao cấp",
                            Name = "MacBook Pro M2",
                            Price = 1999.99m,
                            StockQuantity = 50,
                            UpdatedAt = new DateTime(2025, 4, 23, 15, 23, 11, 154, DateTimeKind.Utc).AddTicks(4860)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
